package drawingbot.files.json;

import drawingbot.javafx.GenericPreset;

import java.util.ArrayList;
import java.util.List;

/**
 * A simple json file, used to store the data generated by a {@link IPresetLoader}
 * Used for restoring the order / the hiding of system presets
 */
@JsonData
public class PresetLoaderDataFile {

    public List<GenericPreset<?>> jsonMap;
    public List<String> presetOrder;
    public List<String> hiddenSystemPresets;

    public PresetLoaderDataFile(){
        this.jsonMap = new ArrayList<>();
        this.presetOrder = new ArrayList<>();
        this.hiddenSystemPresets = new ArrayList<>();
    }
}
