package drawingbot;//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import drawingbot.pfm.PFMLoaders;
import drawingbot.utils.EnumDisplayMode;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
/**
 * @author  Administrator
 * @created January 17, 2021
 */
public class DrawingBotV3Frame extends JFrame {

JPanel mainPanel;
JButton btOpen;
JButton btSave;
JComboBox<PFMLoaders> pfmLoadersJComboBox;
JComboBox<EnumDisplayMode> displayModeJComboBox;

/**
 */
public DrawingBotV3Frame()
{
   super( "EMBED TIMES" );
   mainPanel = new JPanel();
   GridBagLayout panelLayout = new GridBagLayout();
   GridBagConstraints grid = new GridBagConstraints();
   mainPanel.setLayout( panelLayout );

   btOpen = new JButton( "Open"  );
   grid.gridx = 1;
   grid.gridy = 1;
   grid.gridwidth = 5;
   grid.gridheight = 1;
   grid.fill = GridBagConstraints.BOTH;
   grid.weightx = 1;
   grid.weighty = 0;
   grid.anchor = GridBagConstraints.NORTH;
   panelLayout.setConstraints( btOpen, grid );
   mainPanel.add( btOpen );

   btSave = new JButton( "Save"  );
   btSave.addActionListener(l -> DrawingBotV3.INSTANCE.rotate());
   grid.gridx = 6;
   grid.gridy = 1;
   grid.gridwidth = 5;
   grid.gridheight = 1;
   grid.fill = GridBagConstraints.BOTH;
   grid.weightx = 1;
   grid.weighty = 0;
   grid.anchor = GridBagConstraints.NORTH;
   panelLayout.setConstraints( btSave, grid );
   mainPanel.add( btSave );

   pfmLoadersJComboBox = new JComboBox<>(PFMLoaders.values());
   pfmLoadersJComboBox.addActionListener(l -> DrawingBotV3.INSTANCE.action_changePFM(pfmLoadersJComboBox.getItemAt(pfmLoadersJComboBox.getSelectedIndex())));

   grid.gridx = 11;
   grid.gridy = 1;
   grid.gridwidth = 6;
   grid.gridheight = 1;
   grid.fill = GridBagConstraints.BOTH;
   grid.weightx = 1;
   grid.weighty = 0;
   grid.anchor = GridBagConstraints.NORTH;
   panelLayout.setConstraints(pfmLoadersJComboBox, grid );
   mainPanel.add(pfmLoadersJComboBox);

   displayModeJComboBox = new JComboBox<>( EnumDisplayMode.values() );
   pfmLoadersJComboBox.addActionListener(l -> DrawingBotV3.INSTANCE.changeDisplayMode(displayModeJComboBox.getItemAt(displayModeJComboBox.getSelectedIndex())));
   grid.gridx = 17;
   grid.gridy = 1;
   grid.gridwidth = 4;
   grid.gridheight = 1;
   grid.fill = GridBagConstraints.BOTH;
   grid.weightx = 1;
   grid.weighty = 0;
   grid.anchor = GridBagConstraints.NORTH;
   panelLayout.setConstraints(displayModeJComboBox, grid );
   mainPanel.add(displayModeJComboBox);

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane(mainPanel);
   pack();
   setVisible( true );
} 
} 
