package drawingbot.helpers;// Regex used in sublime to clean up html from:
// Source data:  https://imaginationinternationalinc.com/copic/store/color-picker/
//
// ^.*color:
// ; cursor.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*<h5>
// </h5>\n.*<p>
// </p>\n.*clearfix.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n
// ^(.*?),(.*?),(.*)
// sketch_color.put("$2"), color($1));  sketch_name.put("$2"), "$3");


///////////////////////////////////////////////////////////////////////////////////////////////////////

import drawingbot.DrawingBotV3;

import static processing.core.PApplet.*;
import java.util.HashMap;
import java.util.Map;

public class CopicPenHelper {
    public static DrawingBotV3 app = DrawingBotV3.INSTANCE;

    public HashMap<String, Integer> sketch_color;
    public HashMap<String, String> sketch_name;
    public HashMap<String, Integer> original_color;
    public HashMap<String, String> original_name;

    public static final String[][] copic_sets = {
            {"100", "N10", "N8", "N6", "N4", "N2"},       // Dark Greys
            {"100", "100", "N7", "N5", "N3", "N2"},       // Light Greys
            {"100", "W10", "W8", "W6", "W4", "W2"},       // Warm Greys
            {"100", "C10", "C8", "C6", "C4", "C2"},       // Cool Greys
            {"100", "100", "C7", "W5", "C3", "W2"},       // Mixed Greys
            {"100", "100", "W7", "C5", "W3", "C2"},       // Mixed Greys
            {"100", "100", "E49", "E27", "E13", "E00"},   // Browns
            {"100", "100", "E49", "E27", "E13", "N2"},    // Dark Grey Browns
            {"100", "100", "E49", "E27", "N4", "N2"},     // Browns
            {"100", "100", "E49", "N6", "N4", "N2"},      // Dark Grey Browns
            {"100", "100", "B37", "N6", "N4", "N2"},      // Dark Grey Blues
            {"100", "100", "R59", "N6", "N4", "N2"},      // Dark Grey Red
            {"100", "100", "G29", "N6", "N4", "N2"},      // Dark Grey Violet
            {"100", "100", "YR09", "N6", "N4", "N2"},     // Dark Grey Orange
            {"100", "100", "B39", "G28", "B26", "G14"},   // Blue Green
            {"100", "100", "B39", "V09", "B02", "V04"},   // Purples
            {"100", "100", "R29", "R27", "R24", "R20"},   // Reds
            {"100", "E29", "YG99", "Y17", "YG03", "Y11"} // Yellow, green
    };

    public CopicPenHelper() {
        sketch_color = new HashMap <String, Integer> ();
        sketch_name = new HashMap <String, String> ();
        original_color = new HashMap <String, Integer> ();
        original_name = new HashMap <String, String> ();

        this.sketch_color.put("0", app.color(-1));
        this.sketch_name.put("0", "Colorless Blender");
        this.sketch_color.put("100", app.color(-13554901));
        this.sketch_name.put("100", "Black");
        this.sketch_color.put("110", app.color(-16578808));
        this.sketch_name.put("110", "Special Black");
        this.sketch_color.put("B0000", app.color(-984578));
        this.sketch_name.put("B0000", "Pale Celestine");
        this.sketch_color.put("B000", app.color(-1641227));
        this.sketch_name.put("B000", "Pale Porcelain Blue");
        this.sketch_color.put("B00", app.color(-2232076));
        this.sketch_name.put("B00", "Frost Blue");
        this.sketch_color.put("B01", app.color(-2691342));
        this.sketch_name.put("B01", "Mint Blue");
        this.sketch_color.put("B02", app.color(-4987919));
        this.sketch_name.put("B02", "Robin&#39;s Egg Blue");
        this.sketch_color.put("B04", app.color(-9187354));
        this.sketch_name.put("B04", "Tahitian Blue");
        this.sketch_color.put("B05", app.color(-12532250));
        this.sketch_name.put("B05", "Process Blue");
        this.sketch_color.put("B06", app.color(-16731162));
        this.sketch_name.put("B06", "Peacok Blue");
        this.sketch_color.put("B12", app.color(-3610896));
        this.sketch_name.put("B12", "Ice Blue");
        this.sketch_color.put("B14", app.color(-9318421));
        this.sketch_name.put("B14", "Light Blue");
        this.sketch_color.put("B16", app.color(-16728854));
        this.sketch_name.put("B16", "Cyanine Blue");
        this.sketch_color.put("B18", app.color(-14841141));
        this.sketch_name.put("B18", "Lapis Lazuli");
        this.sketch_color.put("B21", app.color(-2363911));
        this.sketch_name.put("B21", "Baby Blue");
        this.sketch_color.put("B23", app.color(-7159064));
        this.sketch_name.put("B23", "Phthalo Blue");
        this.sketch_color.put("B24", app.color(-7680269));
        this.sketch_name.put("B24", "Sky");
        this.sketch_color.put("B26", app.color(-10112029));
        this.sketch_name.put("B26", "Cobalt Blue");
        this.sketch_color.put("B28", app.color(-15110730));
        this.sketch_name.put("B28", "Royal Blue");
        this.sketch_color.put("B29", app.color(-16681023));
        this.sketch_name.put("B29", "Ultramarine");
        this.sketch_color.put("B32", app.color(-1904649));
        this.sketch_name.put("B32", "Pale Blue");
        this.sketch_color.put("B34", app.color(-8207379));
        this.sketch_name.put("B34", "Manganese Blue");
        this.sketch_color.put("B37", app.color(-15372380));
        this.sketch_name.put("B37", "Antwerp Blue");
        this.sketch_color.put("B39", app.color(-13933399));
        this.sketch_name.put("B39", "Prussian Blue");
        this.sketch_color.put("B41", app.color(-1904389));
        this.sketch_name.put("B41", "Powder Blue");
        this.sketch_color.put("B45", app.color(-9060118));
        this.sketch_name.put("B45", "Smoky Blue");
        this.sketch_color.put("B52", app.color(-5386788));
        this.sketch_name.put("B52", "Soft Greenish Blue");
        this.sketch_color.put("B60", app.color(-2432525));
        this.sketch_name.put("B60", "Pale Blue Gray");
        this.sketch_color.put("B63", app.color(-5784608));
        this.sketch_name.put("B63", "Light Hydrangea");
        this.sketch_color.put("B66", app.color(-9926459));
        this.sketch_name.put("B66", "Clematis");
        this.sketch_color.put("B69", app.color(-14588498));
        this.sketch_name.put("B69", "Stratospheric Blue");
        this.sketch_color.put("B79", app.color(-12892259));
        this.sketch_name.put("B79", "Iris");
        this.sketch_color.put("B91", app.color(-2759957));
        this.sketch_name.put("B91", "Pale Grayish Blue");
        this.sketch_color.put("B93", app.color(-6962726));
        this.sketch_name.put("B93", "Light Crockery Blue");
        this.sketch_color.put("B95", app.color(-9132090));
        this.sketch_name.put("B95", "Light Grayish Cobalt");
        this.sketch_color.put("B97", app.color(-12223846));
        this.sketch_name.put("B97", "Night Blue");
        this.sketch_color.put("B99", app.color(-15772546));
        this.sketch_name.put("B99", "Agate");
        this.sketch_color.put("BG0000", app.color(-1050381));
        this.sketch_name.put("BG0000", "Snow Green");
        this.sketch_color.put("BG000", app.color(-1706771));
        this.sketch_name.put("BG000", "Pale Aqua");
        this.sketch_color.put("BG01", app.color(-3676422));
        this.sketch_name.put("BG01", "Aqua Blue");
        this.sketch_color.put("BG02", app.color(-3741462));
        this.sketch_name.put("BG02", "New Blue");
        this.sketch_color.put("BG05", app.color(-8138015));
        this.sketch_name.put("BG05", "Holiday Blue");
        this.sketch_color.put("BG07", app.color(-14829362));
        this.sketch_name.put("BG07", "Petroleum Blue");
        this.sketch_color.put("BG09", app.color(-16666167));
        this.sketch_name.put("BG09", "Blue Green");
        this.sketch_color.put("BG10", app.color(-2297617));
        this.sketch_name.put("BG10", "Cool Shadow");
        this.sketch_color.put("BG11", app.color(-3216399));
        this.sketch_name.put("BG11", "Moon White");
        this.sketch_color.put("BG13", app.color(-3872791));
        this.sketch_name.put("BG13", "Mint Green");
        this.sketch_color.put("BG15", app.color(-6235694));
        this.sketch_name.put("BG15", "Aqua");
        this.sketch_color.put("BG18", app.color(-13123408));
        this.sketch_name.put("BG18", "Teal Blue");
        this.sketch_color.put("BG23", app.color(-4332067));
        this.sketch_name.put("BG23", "Coral Sea");
        this.sketch_color.put("BG32", app.color(-4398377));
        this.sketch_name.put("BG32", "Aqua Mint");
        this.sketch_color.put("BG34", app.color(-6038825));
        this.sketch_name.put("BG34", "Horizon Green");
        this.sketch_color.put("BG45", app.color(-5251105));
        this.sketch_name.put("BG45", "Nile Blue");
        this.sketch_color.put("BG49", app.color(-16730439));
        this.sketch_name.put("BG49", "Duck Blue");
        this.sketch_color.put("BG53", app.color(-5451823));
        this.sketch_name.put("BG53", "Ice Mint");
        this.sketch_color.put("BG57", app.color(-10174786));
        this.sketch_name.put("BG57", "Sketch Jasper");
        this.sketch_color.put("BG70", app.color(-2429714));
        this.sketch_name.put("BG70", "Ocean Mist");
        this.sketch_color.put("BG72", app.color(-9127749));
        this.sketch_name.put("BG72", "Ice Ocean");
        this.sketch_color.put("BG75", app.color(-10907250));
        this.sketch_name.put("BG75", "Abyss Green");
        this.sketch_color.put("BG78", app.color(-11964309));
        this.sketch_name.put("BG78", "Bronze");
        this.sketch_color.put("BG90", app.color(-1511961));
        this.sketch_name.put("BG90", "Sketch Gray Sky");
        this.sketch_color.put("BG93", app.color(-4537927));
        this.sketch_name.put("BG93", "Green Gray");
        this.sketch_color.put("BG96", app.color(-8281455));
        this.sketch_name.put("BG96", "Bush");
        this.sketch_color.put("BG99", app.color(-9528441));
        this.sketch_name.put("BG99", "Flagstone Blue");
        this.sketch_color.put("BV0000", app.color(-1382414));
        this.sketch_name.put("BV0000", "Sketch Pale Thistle");
        this.sketch_color.put("BV000", app.color(-1382414));
        this.sketch_name.put("BV000", "Iridescent Mauve");
        this.sketch_color.put("BV00", app.color(-2040595));
        this.sketch_name.put("BV00", "Mauve Shadow");
        this.sketch_color.put("BV01", app.color(-3880474));
        this.sketch_name.put("BV01", "Viola");
        this.sketch_color.put("BV02", app.color(-5588773));
        this.sketch_name.put("BV02", "Prune");
        this.sketch_color.put("BV04", app.color(-8611890));
        this.sketch_name.put("BV04", "Blue Berry");
        this.sketch_color.put("BV08", app.color(-6455623));
        this.sketch_name.put("BV08", "Blue Violet");
        this.sketch_color.put("BV11", app.color(-2829592));
        this.sketch_name.put("BV11", "Soft Violet");
        this.sketch_color.put("BV13", app.color(-8089144));
        this.sketch_name.put("BV13", "Hydrangea Blue");
        this.sketch_color.put("BV17", app.color(-9534275));
        this.sketch_name.put("BV17", "Deep Reddish Blue");
        this.sketch_color.put("BV20", app.color(-3154959));
        this.sketch_name.put("BV20", "Dull Lavender");
        this.sketch_color.put("BV23", app.color(-5127971));
        this.sketch_name.put("BV23", "Grayish Lavender");
        this.sketch_color.put("BV25", app.color(-8289113));
        this.sketch_name.put("BV25", "Grayish Violet");
        this.sketch_color.put("BV29", app.color(-13089448));
        this.sketch_name.put("BV29", "Slate");
        this.sketch_color.put("BV31", app.color(-1382414));
        this.sketch_name.put("BV31", "Pale Lavender");
        this.sketch_color.put("BV34", app.color(-6314052));
        this.sketch_name.put("BV34", "Sketch Bluebell");
        this.sketch_color.put("C00", app.color(-1511181));
        this.sketch_name.put("C00", "Cool Gray");
        this.sketch_color.put("C0", app.color(-2037779));
        this.sketch_name.put("C0", "Cool Gray");
        this.sketch_color.put("C10", app.color(-14669007));
        this.sketch_name.put("C10", "Cool Gray");
        this.sketch_color.put("C1", app.color(-2432024));
        this.sketch_name.put("C1", "Cool Gray No. 1");
        this.sketch_color.put("C2", app.color(-3352611));
        this.sketch_name.put("C2", "Cool Gray");
        this.sketch_color.put("C3", app.color(-4076334));
        this.sketch_name.put("C3", "Cool Gray No. 3");
        this.sketch_color.put("C4", app.color(-5851971));
        this.sketch_name.put("C4", "Cool Gray");
        this.sketch_color.put("C5", app.color(-7167829));
        this.sketch_name.put("C5", "Cool Gray No. 5");
        this.sketch_color.put("C6", app.color(-8680298));
        this.sketch_name.put("C6", "Cool Gray");
        this.sketch_color.put("C7", app.color(-10260359));
        this.sketch_name.put("C7", "Cool Gray No. 7");
        this.sketch_color.put("C8", app.color(-11313818));
        this.sketch_name.put("C8", "Cool Gray");
        this.sketch_color.put("C9", app.color(-12826803));
        this.sketch_name.put("C9", "Cool Gray");
        this.sketch_color.put("E0000", app.color(-1292));
        this.sketch_name.put("E0000", "Floral White");
        this.sketch_color.put("E000", app.color(-68114));
        this.sketch_name.put("E000", "Pale Fruit Pink");
        this.sketch_color.put("E00", app.color(-134166));
        this.sketch_name.put("E00", "Cotton Pearl");
        this.sketch_color.put("E01", app.color(-4380));
        this.sketch_name.put("E01", "Pink Flamingo");
        this.sketch_color.put("E02", app.color(-70432));
        this.sketch_name.put("E02", "Fruit Pink");
        this.sketch_color.put("E04", app.color(-1786684));
        this.sketch_name.put("E04", "Lipstick Natural");
        this.sketch_color.put("E07", app.color(-3374742));
        this.sketch_name.put("E07", "Light Mahogany");
        this.sketch_color.put("E08", app.color(-3513005));
        this.sketch_name.put("E08", "Brown");
        this.sketch_color.put("E09", app.color(-2528689));
        this.sketch_name.put("E09", "Burnt Sienna");
        this.sketch_color.put("E11", app.color(-71210));
        this.sketch_name.put("E11", "Barley Beige");
        this.sketch_color.put("E13", app.color(-1456721));
        this.sketch_name.put("E13", "Light Suntan");
        this.sketch_color.put("E15", app.color(-279667));
        this.sketch_name.put("E15", "Dark Suntan");
        this.sketch_color.put("E17", app.color(-4694185));
        this.sketch_name.put("E17", "Reddish Brass");
        this.sketch_color.put("E18", app.color(-7842995));
        this.sketch_name.put("E18", "Copper");
        this.sketch_color.put("E19", app.color(-3911112));
        this.sketch_name.put("E19", "Redwood");
        this.sketch_color.put("E21", app.color(-138553));
        this.sketch_name.put("E21", "Soft Sun");
        this.sketch_color.put("E23", app.color(-1258831));
        this.sketch_name.put("E23", "Hazelnut");
        this.sketch_color.put("E25", app.color(-2972542));
        this.sketch_name.put("E25", "Caribe Cocoa");
        this.sketch_color.put("E27", app.color(-6719901));
        this.sketch_name.put("E27", "Milk Chocolate");
        this.sketch_color.put("E29", app.color(-7846346));
        this.sketch_name.put("E29", "Burnt Umber");
        this.sketch_color.put("E30", app.color(-528170));
        this.sketch_name.put("E30", "Bisque");
        this.sketch_color.put("E31", app.color(-858418));
        this.sketch_name.put("E31", "Brick Beige");
        this.sketch_color.put("E33", app.color(-798031));
        this.sketch_name.put("E33", "Sand");
        this.sketch_color.put("E34", app.color(-996698));
        this.sketch_name.put("E34", "Toast");
        this.sketch_color.put("E35", app.color(-1653853));
        this.sketch_name.put("E35", "Chamois");
        this.sketch_color.put("E37", app.color(-3370663));
        this.sketch_name.put("E37", "Sepia");
        this.sketch_color.put("E39", app.color(-3836865));
        this.sketch_name.put("E39", "Leather");
        this.sketch_color.put("E40", app.color(-857892));
        this.sketch_name.put("E40", "Brick White");
        this.sketch_color.put("E41", app.color(-69151));
        this.sketch_name.put("E41", "Pearl White");
        this.sketch_color.put("E42", app.color(-791847));
        this.sketch_name.put("E42", "Sand White");
        this.sketch_color.put("E43", app.color(-1516867));
        this.sketch_name.put("E43", "Dull Ivory");
        this.sketch_color.put("E44", app.color(-3819095));
        this.sketch_name.put("E44", "Clay");
        this.sketch_color.put("E47", app.color(-7704999));
        this.sketch_name.put("E47", "Dark Brown");
        this.sketch_color.put("E49", app.color(-10269636));
        this.sketch_name.put("E49", "Dark Bark");
        this.sketch_color.put("E50", app.color(-726032));
        this.sketch_name.put("E50", "Egg Shell");
        this.sketch_color.put("E51", app.color(-70442));
        this.sketch_name.put("E51", "Milky White");
        this.sketch_color.put("E53", app.color(-792893));
        this.sketch_name.put("E53", "Raw Silk");
        this.sketch_color.put("E55", app.color(-925767));
        this.sketch_name.put("E55", "Light Camel");
        this.sketch_color.put("E57", app.color(-5143208));
        this.sketch_name.put("E57", "Light Walnut");
        this.sketch_color.put("E59", app.color(-6652052));
        this.sketch_name.put("E59", "Walnut");
        this.sketch_color.put("E70", app.color(-1053978));
        this.sketch_name.put("E70", "Ash Rose");
        this.sketch_color.put("E71", app.color(-1910829));
        this.sketch_name.put("E71", "Champagne");
        this.sketch_color.put("E74", app.color(-6192004));
        this.sketch_name.put("E74", "Cocoa Brown");
        this.sketch_color.put("E77", app.color(-8429490));
        this.sketch_name.put("E77", "Maroon");
        this.sketch_color.put("E79", app.color(-11916254));
        this.sketch_name.put("E79", "Cashew");
        this.sketch_color.put("E81", app.color(-989502));
        this.sketch_name.put("E81", "Ivory");
        this.sketch_color.put("E84", app.color(-5333120));
        this.sketch_name.put("E84", "- Sketch Khaki");
        this.sketch_color.put("E87", app.color(-9478067));
        this.sketch_name.put("E87", "Fig");
        this.sketch_color.put("E89", app.color(-10860231));
        this.sketch_name.put("E89", "- Sketch Pecan");
        this.sketch_color.put("E93", app.color(-77127));
        this.sketch_name.put("E93", "Tea Rose");
        this.sketch_color.put("E95", app.color(-213890));
        this.sketch_name.put("E95", "Tea Orange");
        this.sketch_color.put("E97", app.color(-1205155));
        this.sketch_name.put("E97", "Deep Orange");
        this.sketch_color.put("E99", app.color(-4956108));
        this.sketch_name.put("E99", "Baked Clay");
        this.sketch_color.put("FB2", app.color(-16412720));
        this.sketch_name.put("FB2", "Fluorescent Dull Blue");
        this.sketch_color.put("FBG2", app.color(-10302488));
        this.sketch_name.put("FBG2", "Fluorescent Dull Blue Green");
        this.sketch_color.put("FRV1", app.color(-678969));
        this.sketch_name.put("FRV1", "Fluorescent Pink");
        this.sketch_color.put("FV2", app.color(-8424266));
        this.sketch_name.put("FV2", "Fluorescent Dull Violet");
        this.sketch_color.put("FY1", app.color(-2409));
        this.sketch_name.put("FY1", "Fluorescent Yellow Orange");
        this.sketch_color.put("FYG1", app.color(-6369981));
        this.sketch_name.put("FYG1", "Fluorescent Yellow");
        this.sketch_color.put("FYG2", app.color(-6369981));
        this.sketch_name.put("FYG2", "Fluorescent Dull Yellow Green");
        this.sketch_color.put("FYR1", app.color(-78695));
        this.sketch_name.put("FYR1", "Fluorescent Orange");
        this.sketch_color.put("G0000", app.color(-919565));
        this.sketch_name.put("G0000", "Crystal Opal");
        this.sketch_color.put("G000", app.color(-1378835));
        this.sketch_name.put("G000", "Pale Green");
        this.sketch_color.put("G00", app.color(-1838355));
        this.sketch_name.put("G00", "Jade Green");
        this.sketch_color.put("G02", app.color(-3151661));
        this.sketch_name.put("G02", "Spectrum Green");
        this.sketch_color.put("G03", app.color(-4793700));
        this.sketch_name.put("G03", "Meadow Green");
        this.sketch_color.put("G05", app.color(-9846661));
        this.sketch_name.put("G05", "Emerald Green");
        this.sketch_color.put("G07", app.color(-8665738));
        this.sketch_name.put("G07", "Nile Green");
        this.sketch_color.put("G09", app.color(-8731547));
        this.sketch_name.put("G09", "Veronese Green");
        this.sketch_color.put("G12", app.color(-2955068));
        this.sketch_name.put("G12", "Sea Green");
        this.sketch_color.put("G14", app.color(-6828144));
        this.sketch_name.put("G14", "Apple Green");
        this.sketch_color.put("G16", app.color(-10436200));
        this.sketch_name.put("G16", "Malachite");
        this.sketch_color.put("G17", app.color(-15420547));
        this.sketch_name.put("G17", "Forest Green");
        this.sketch_color.put("G19", app.color(-13780598));
        this.sketch_name.put("G19", "Bright Parrot Green");
        this.sketch_color.put("G20", app.color(-1181989));
        this.sketch_name.put("G20", "Wax White");
        this.sketch_color.put("G21", app.color(-3873587));
        this.sketch_name.put("G21", "Lime Green");
        this.sketch_color.put("G24", app.color(-3940172));
        this.sketch_name.put("G24", "Willow");
        this.sketch_color.put("G28", app.color(-15625118));
        this.sketch_name.put("G28", "Ocean Green");
        this.sketch_color.put("G29", app.color(-15106979));
        this.sketch_name.put("G29", "Pine Tree Green");
        this.sketch_color.put("G40", app.color(-1773089));
        this.sketch_name.put("G40", "Dim Green");
        this.sketch_color.put("G43", app.color(-2627672));
        this.sketch_name.put("G43", "Various Pistachio");
        this.sketch_color.put("G46", app.color(-11035020));
        this.sketch_name.put("G46", "Sketch Mistletoe");
        this.sketch_color.put("G82", app.color(-3351879));
        this.sketch_name.put("G82", "Spring Dim Green");
        this.sketch_color.put("G85", app.color(-6437974));
        this.sketch_name.put("G85", "Verdigris");
        this.sketch_color.put("G94", app.color(-6772858));
        this.sketch_name.put("G94", "Grayish Olive");
        this.sketch_color.put("G99", app.color(-10518982));
        this.sketch_name.put("G99", "Olive");
        this.sketch_color.put("N0", app.color(-1249555));
        this.sketch_name.put("N0", "Neutral Gray");
        this.sketch_color.put("N10", app.color(-13553872));
        this.sketch_name.put("N10", "Neutral Gray");
        this.sketch_color.put("N1", app.color(-1907739));
        this.sketch_name.put("N1", "Neutral Gray");
        this.sketch_color.put("N2", app.color(-2434083));
        this.sketch_name.put("N2", "Neutral Gray");
        this.sketch_color.put("N3", app.color(-3026220));
        this.sketch_name.put("N3", "Neutral Gray");
        this.sketch_color.put("N4", app.color(-4407871));
        this.sketch_name.put("N4", "Neutral Gray");
        this.sketch_color.put("N5", app.color(-5723731));
        this.sketch_name.put("N5", "Neutral Gray");
        this.sketch_color.put("N6", app.color(-7039591));
        this.sketch_name.put("N6", "Neutral Gray");
        this.sketch_color.put("N7", app.color(-8947588));
        this.sketch_name.put("N7", "Neutral Gray");
        this.sketch_color.put("N8", app.color(-10263450));
        this.sketch_name.put("N8", "Neutral Gray");
        this.sketch_color.put("N9", app.color(-11776689));
        this.sketch_name.put("N9", "Neutral Gray");
        this.sketch_color.put("R0000", app.color(-68625));
        this.sketch_name.put("R0000", "Pink Beryl");
        this.sketch_color.put("R000", app.color(-69401));
        this.sketch_name.put("R000", "Cherry White");
        this.sketch_color.put("R00", app.color(-70943));
        this.sketch_name.put("R00", "Pinkish White");
        this.sketch_color.put("R01", app.color(-139048));
        this.sketch_name.put("R01", "Pinkish Vanilla");
        this.sketch_color.put("R02", app.color(-142393));
        this.sketch_name.put("R02", "Rose Salmon");
        this.sketch_color.put("R05", app.color(-617861));
        this.sketch_name.put("R05", "Salmon Red");
        this.sketch_color.put("R08", app.color(-891052));
        this.sketch_name.put("R08", "Vermilion");
        this.sketch_color.put("R11", app.color(-138795));
        this.sketch_name.put("R11", "Pale Cherry Pink");
        this.sketch_color.put("R12", app.color(-207935));
        this.sketch_name.put("R12", "Light Tea Rose");
        this.sketch_color.put("R14", app.color(-681070));
        this.sketch_name.put("R14", "Light Rouge");
        this.sketch_color.put("R17", app.color(-752532));
        this.sketch_name.put("R17", "Lipstick Orange");
        this.sketch_color.put("R20", app.color(-206897));
        this.sketch_name.put("R20", "Blush");
        this.sketch_color.put("R21", app.color(-343626));
        this.sketch_name.put("R21", "Sardonyx");
        this.sketch_color.put("R22", app.color(-477263));
        this.sketch_name.put("R22", "Light Prawn");
        this.sketch_color.put("R24", app.color(-887431));
        this.sketch_name.put("R24", "Prawn");
        this.sketch_color.put("R27", app.color(-962462));
        this.sketch_name.put("R27", "Cadmium Red");
        this.sketch_color.put("R29", app.color(-1239221));
        this.sketch_name.put("R29", "Lipstick Red");
        this.sketch_color.put("R30", app.color(-203809));
        this.sketch_name.put("R30", "Pale Yellowish Pink");
        this.sketch_color.put("R32", app.color(-343622));
        this.sketch_name.put("R32", "Peach");
        this.sketch_color.put("R35", app.color(-888443));
        this.sketch_name.put("R35", "Coral");
        this.sketch_color.put("R37", app.color(-1545100));
        this.sketch_name.put("R37", "Carmine");
        this.sketch_color.put("R39", app.color(-3454854));
        this.sketch_name.put("R39", "Garnet");
        this.sketch_color.put("R43", app.color(-1145714));
        this.sketch_name.put("R43", "Bougainvillaea");
        this.sketch_color.put("R46", app.color(-2077335));
        this.sketch_name.put("R46", "Strong Red");
        this.sketch_color.put("R56", app.color(-2982763));
        this.sketch_name.put("R56", "Currant");
        this.sketch_color.put("R59", app.color(-4763792));
        this.sketch_name.put("R59", "Cardinal");
        this.sketch_color.put("R81", app.color(-931626));
        this.sketch_name.put("R81", "Rose Pink");
        this.sketch_color.put("R83", app.color(-942919));
        this.sketch_name.put("R83", "Rose Mist");
        this.sketch_color.put("R85", app.color(-2921837));
        this.sketch_name.put("R85", "Rose Red");
        this.sketch_color.put("R89", app.color(-8574142));
        this.sketch_name.put("R89", "Dark Red");
        this.sketch_color.put("RV0000", app.color(-857355));
        this.sketch_name.put("RV0000", "Evening Primrose");
        this.sketch_color.put("RV000", app.color(-728338));
        this.sketch_name.put("RV000", "Pale Purple");
        this.sketch_color.put("RV00", app.color(-926998));
        this.sketch_name.put("RV00", "Water Lily");
        this.sketch_color.put("RV02", app.color(-338458));
        this.sketch_name.put("RV02", "Sugared Almond Pink");
        this.sketch_color.put("RV04", app.color(-613441));
        this.sketch_name.put("RV04", "Shock  Pink");
        this.sketch_color.put("RV06", app.color(-817489));
        this.sketch_name.put("RV06", "Cerise");
        this.sketch_color.put("RV09", app.color(-2002516));
        this.sketch_name.put("RV09", "Fuchsia");
        this.sketch_color.put("RV10", app.color(-135948));
        this.sketch_name.put("RV10", "Pale Pink");
        this.sketch_color.put("RV11", app.color(-272675));
        this.sketch_name.put("RV11", "Pink");
        this.sketch_color.put("RV13", app.color(-407081));
        this.sketch_name.put("RV13", "Tender Pink");
        this.sketch_color.put("RV14", app.color(-748105));
        this.sketch_name.put("RV14", "Begonia Pink");
        this.sketch_color.put("RV17", app.color(-2392397));
        this.sketch_name.put("RV17", "Deep Magenta");
        this.sketch_color.put("RV19", app.color(-2987862));
        this.sketch_name.put("RV19", "Red Violet");
        this.sketch_color.put("RV21", app.color(-136985));
        this.sketch_name.put("RV21", "Light Pink");
        this.sketch_color.put("RV23", app.color(-476471));
        this.sketch_name.put("RV23", "Pure Pink");
        this.sketch_color.put("RV25", app.color(-748610));
        this.sketch_name.put("RV25", "Dog Rose Flower");
        this.sketch_color.put("RV29", app.color(-1095552));
        this.sketch_name.put("RV29", "Crimson");
        this.sketch_color.put("RV32", app.color(-338994));
        this.sketch_name.put("RV32", "Shadow Pink");
        this.sketch_color.put("RV34", app.color(-413778));
        this.sketch_name.put("RV34", "Dark Pink");
        this.sketch_color.put("RV42", app.color(-476234));
        this.sketch_name.put("RV42", "Salmon Pink");
        this.sketch_color.put("RV52", app.color(-406818));
        this.sketch_name.put("RV52", "Various Cotton Candy");
        this.sketch_color.put("RV55", app.color(-1464886));
        this.sketch_name.put("RV55", "Hollyhock");
        this.sketch_color.put("RV63", app.color(-3105362));
        this.sketch_name.put("RV63", "Begonia");
        this.sketch_color.put("RV66", app.color(-4691324));
        this.sketch_name.put("RV66", "Raspberry");
        this.sketch_color.put("RV69", app.color(-7645330));
        this.sketch_name.put("RV69", "Peony");
        this.sketch_color.put("RV91", app.color(-1649438));
        this.sketch_name.put("RV91", "Garyish Cherry");
        this.sketch_color.put("RV93", app.color(-1591604));
        this.sketch_name.put("RV93", "Smokey Purple");
        this.sketch_color.put("RV95", app.color(-4815711));
        this.sketch_name.put("RV95", "Baby Blossoms");
        this.sketch_color.put("RV99", app.color(-10860456));
        this.sketch_name.put("RV99", "Argyle Purple");
        this.sketch_color.put("T0", app.color(-1249555));
        this.sketch_name.put("T0", "Toner Gray");
        this.sketch_color.put("T10", app.color(-13488595));
        this.sketch_name.put("T10", "Toner Gray");
        this.sketch_color.put("T1", app.color(-1381656));
        this.sketch_name.put("T1", "Toner Gray");
        this.sketch_color.put("T2", app.color(-2039586));
        this.sketch_name.put("T2", "Toner Gray");
        this.sketch_color.put("T3", app.color(-3026228));
        this.sketch_name.put("T3", "Toner Gray");
        this.sketch_color.put("T4", app.color(-4408391));
        this.sketch_name.put("T4", "Toner Gray");
        this.sketch_color.put("T5", app.color(-5724253));
        this.sketch_name.put("T5", "Toner Gray");
        this.sketch_color.put("T6", app.color(-7039600));
        this.sketch_name.put("T6", "Toner Gray");
        this.sketch_color.put("T7", app.color(-8948108));
        this.sketch_name.put("T7", "Toner Gray");
        this.sketch_color.put("T8", app.color(-10263457));
        this.sketch_name.put("T8", "Toner Gray");
        this.sketch_color.put("T9", app.color(-11777207));
        this.sketch_name.put("T9", "Toner Gray");
        this.sketch_color.put("V0000", app.color(-987658));
        this.sketch_name.put("V0000", "Rose Quartz");
        this.sketch_color.put("V000", app.color(-1448461));
        this.sketch_name.put("V000", "Pale Heath");
        this.sketch_color.put("V01", app.color(-1785383));
        this.sketch_name.put("V01", "Heath");
        this.sketch_color.put("V04", app.color(-1660210));
        this.sketch_name.put("V04", "Lilac");
        this.sketch_color.put("V05", app.color(-1923382));
        this.sketch_name.put("V05", "Azalea");
        this.sketch_color.put("V06", app.color(-3238462));
        this.sketch_name.put("V06", "Lavender");
        this.sketch_color.put("V09", app.color(-7908191));
        this.sketch_name.put("V09", "Violet");
        this.sketch_color.put("V12", app.color(-1124375));
        this.sketch_name.put("V12", "Pale Lilac");
        this.sketch_color.put("V15", app.color(-2906419));
        this.sketch_name.put("V15", "Mallow");
        this.sketch_color.put("V17", app.color(-6253881));
        this.sketch_name.put("V17", "Amethyst");
        this.sketch_color.put("V20", app.color(-1908499));
        this.sketch_name.put("V20", "Wisteria");
        this.sketch_color.put("V22", app.color(-5066288));
        this.sketch_name.put("V22", "Sketch Ash Lavender");
        this.sketch_color.put("V25", app.color(-8028243));
        this.sketch_name.put("V25", "Pale Blackberry");
        this.sketch_color.put("V28", app.color(-9738610));
        this.sketch_name.put("V28", "Sketch Eggplant");
        this.sketch_color.put("V91", app.color(-1522480));
        this.sketch_name.put("V91", "Pale Grape");
        this.sketch_color.put("V93", app.color(-1719845));
        this.sketch_name.put("V93", "Early Grape");
        this.sketch_color.put("V95", app.color(-4752216));
        this.sketch_name.put("V95", "Light Grape");
        this.sketch_color.put("V99", app.color(-11386024));
        this.sketch_name.put("V99", "Aubergine");
        this.sketch_color.put("W00", app.color(-789525));
        this.sketch_name.put("W00", "Warm Gray");
        this.sketch_color.put("W0", app.color(-1250076));
        this.sketch_name.put("W0", "Warm Gray");
        this.sketch_color.put("W10", app.color(-13619413));
        this.sketch_name.put("W10", "Warm Gray");
        this.sketch_color.put("W1", app.color(-1579041));
        this.sketch_name.put("W1", "Warm Gray No. 1");
        this.sketch_color.put("W2", app.color(-2236971));
        this.sketch_name.put("W2", "Warm Gray");
        this.sketch_color.put("W3", app.color(-2960694));
        this.sketch_name.put("W3", "Warm Gray No. 3");
        this.sketch_color.put("W4", app.color(-4407881));
        this.sketch_name.put("W4", "Warm Gray");
        this.sketch_color.put("W5", app.color(-5723740));
        this.sketch_name.put("W5", "Warm Gray No. 5");
        this.sketch_color.put("W6", app.color(-7039601));
        this.sketch_name.put("W6", "Warm Gray");
        this.sketch_color.put("W7", app.color(-8947597));
        this.sketch_name.put("W7", "Warm Gray No. 7");
        this.sketch_color.put("W8", app.color(-10263457));
        this.sketch_name.put("W8", "Warm Gray");
        this.sketch_color.put("W9", app.color(-11776696));
        this.sketch_name.put("W9", "Warm Gray");
        this.sketch_color.put("Y0000", app.color(-65804));
        this.sketch_name.put("Y0000", "Yellow Fluorite");
        this.sketch_color.put("Y000", app.color(-791));
        this.sketch_name.put("Y000", "Pale Lemon");
        this.sketch_color.put("Y00", app.color(-66081));
        this.sketch_name.put("Y00", "Barium Yellow");
        this.sketch_color.put("Y02", app.color(-593002));
        this.sketch_name.put("Y02", "Canary Yellow");
        this.sketch_color.put("Y04", app.color(-1186474));
        this.sketch_name.put("Y04", "Acacia");
        this.sketch_color.put("Y06", app.color(-68244));
        this.sketch_name.put("Y06", "Yellow");
        this.sketch_color.put("Y08", app.color(-69120));
        this.sketch_name.put("Y08", "Acid Yellow");
        this.sketch_color.put("Y11", app.color(-1076));
        this.sketch_name.put("Y11", "Pale Yellow");
        this.sketch_color.put("Y13", app.color(-264274));
        this.sketch_name.put("Y13", "Lemon Yellow");
        this.sketch_color.put("Y15", app.color(-71316));
        this.sketch_name.put("Y15", "Cadmium Yellow");
        this.sketch_color.put("Y17", app.color(-7083));
        this.sketch_name.put("Y17", "Golden Yellow");
        this.sketch_color.put("Y18", app.color(-70315));
        this.sketch_name.put("Y18", "Lightning Yellow");
        this.sketch_color.put("Y19", app.color(-5826));
        this.sketch_name.put("Y19", "Napoli Yellow");
        this.sketch_color.put("Y21", app.color(-4414));
        this.sketch_name.put("Y21", "Buttercup Yellow");
        this.sketch_color.put("Y23", app.color(-269389));
        this.sketch_name.put("Y23", "Yellowish Beige");
        this.sketch_color.put("Y26", app.color(-991897));
        this.sketch_name.put("Y26", "Mustard");
        this.sketch_color.put("Y28", app.color(-3495831));
        this.sketch_name.put("Y28", "Lionet Gold");
        this.sketch_color.put("Y32", app.color(-401728));
        this.sketch_name.put("Y32", "Cashmere");
        this.sketch_color.put("Y35", app.color(-10119));
        this.sketch_name.put("Y35", "Maize");
        this.sketch_color.put("Y38", app.color(-11404));
        this.sketch_name.put("Y38", "Honey");
        this.sketch_color.put("YG0000", app.color(-854048));
        this.sketch_name.put("YG0000", "Lily White");
        this.sketch_color.put("YG00", app.color(-1644898));
        this.sketch_name.put("YG00", "Mimosa Yellow");
        this.sketch_color.put("YG01", app.color(-1905742));
        this.sketch_name.put("YG01", "Green Bice");
        this.sketch_color.put("YG03", app.color(-2168150));
        this.sketch_name.put("YG03", "Yellow Green");
        this.sketch_color.put("YG05", app.color(-2693742));
        this.sketch_name.put("YG05", "Salad");
        this.sketch_color.put("YG06", app.color(-3874926));
        this.sketch_name.put("YG06", "Yellowish Green");
        this.sketch_color.put("YG07", app.color(-5910705));
        this.sketch_name.put("YG07", "Acid Green");
        this.sketch_color.put("YG09", app.color(-8207002));
        this.sketch_name.put("YG09", "Lettuce Green");
        this.sketch_color.put("YG11", app.color(-1707824));
        this.sketch_name.put("YG11", "Mignonette");
        this.sketch_color.put("YG13", app.color(-2824801));
        this.sketch_name.put("YG13", "Chartreuse");
        this.sketch_color.put("YG17", app.color(-9256618));
        this.sketch_name.put("YG17", "Grass Green");
        this.sketch_color.put("YG21", app.color(-526658));
        this.sketch_name.put("YG21", "Anise");
        this.sketch_color.put("YG23", app.color(-1643633));
        this.sketch_name.put("YG23", "New Leaf");
        this.sketch_color.put("YG25", app.color(-3088005));
        this.sketch_name.put("YG25", "Celadon Green");
        this.sketch_color.put("YG41", app.color(-2757676));
        this.sketch_name.put("YG41", "Pale Cobalt Green");
        this.sketch_color.put("YG45", app.color(-4924233));
        this.sketch_name.put("YG45", "Cobalt Green");
        this.sketch_color.put("YG61", app.color(-2692650));
        this.sketch_name.put("YG61", "Pale Moss");
        this.sketch_color.put("YG63", app.color(-6239582));
        this.sketch_name.put("YG63", "Pea Green");
        this.sketch_color.put("YG67", app.color(-8274036));
        this.sketch_name.put("YG67", "Moss");
        this.sketch_color.put("YG91", app.color(-2435154));
        this.sketch_name.put("YG91", "Putty");
        this.sketch_color.put("YG93", app.color(-2960740));
        this.sketch_name.put("YG93", "Grayish Yellow");
        this.sketch_color.put("YG95", app.color(-3422626));
        this.sketch_name.put("YG95", "Pale Olive");
        this.sketch_color.put("YG97", app.color(-6975741));
        this.sketch_name.put("YG97", "Spanish Olive");
        this.sketch_color.put("YG99", app.color(-11638251));
        this.sketch_name.put("YG99", "Marine Green");
        this.sketch_color.put("YR0000", app.color(-3099));
        this.sketch_name.put("YR0000", "Pale Chiffon");
        this.sketch_color.put("YR000", app.color(-70440));
        this.sketch_name.put("YR000", "Silk");
        this.sketch_color.put("YR00", app.color(-76099));
        this.sketch_name.put("YR00", "Powder Pink");
        this.sketch_color.put("YR01", app.color(-75070));
        this.sketch_name.put("YR01", "Peach Puff");
        this.sketch_color.put("YR02", app.color(-205627));
        this.sketch_name.put("YR02", "Light Orange");
        this.sketch_color.put("YR04", app.color(-81047));
        this.sketch_name.put("YR04", "Chrome Orange");
        this.sketch_color.put("YR07", app.color(-889031));
        this.sketch_name.put("YR07", "Cadmium Orange");
        this.sketch_color.put("YR09", app.color(-961244));
        this.sketch_name.put("YR09", "Chinese Orange");
        this.sketch_color.put("YR12", app.color(-7514));
        this.sketch_name.put("YR12", "Loquat");
        this.sketch_color.put("YR14", app.color(-79794));
        this.sketch_name.put("YR14", "Caramel");
        this.sketch_color.put("YR15", app.color(-280444));
        this.sketch_name.put("YR15", "Pumpkin Yellow");
        this.sketch_color.put("YR16", app.color(-84183));
        this.sketch_name.put("YR16", "Apricot");
        this.sketch_color.put("YR18", app.color(-890052));
        this.sketch_name.put("YR18", "Sanguine");
        this.sketch_color.put("YR20", app.color(-7745));
        this.sketch_name.put("YR20", "Yellowish Shade");
        this.sketch_color.put("YR21", app.color(-664143));
        this.sketch_name.put("YR21", "Cream");
        this.sketch_color.put("YR23", app.color(-1257589));
        this.sketch_name.put("YR23", "Yellow Ochre");
        this.sketch_color.put("YR24", app.color(-995484));
        this.sketch_name.put("YR24", "Pale Sepia");
        this.sketch_color.put("YR27", app.color(-2791880));
        this.sketch_name.put("YR27", "Tuscan Orange");
        this.sketch_color.put("YR30", app.color(-68902));
        this.sketch_name.put("YR30", "Macadamia Nut");
        this.sketch_color.put("YR31", app.color(-8536));
        this.sketch_name.put("YR31", "Light Reddish Yellow");
        this.sketch_color.put("YR61", app.color(-140604));
        this.sketch_name.put("YR61", "Spring Orange");
        this.sketch_color.put("YR65", app.color(-348576));
        this.sketch_name.put("YR65", "Atoll");
        this.sketch_color.put("YR68", app.color(-823262));
        this.sketch_name.put("YR68", "Orange");
        this.sketch_color.put("YR82", app.color(-145779));
        this.sketch_name.put("YR82", "Mellow Peach");
        this.original_color.put("0", app.color(-1));
        this.original_name.put("0", "Colorless Blender");
        this.original_color.put("100", app.color(-13554901));
        this.original_name.put("100", "Black");
        this.original_color.put("110", app.color(-16578808));
        this.original_name.put("110", "Special Black");
        this.original_color.put("B00", app.color(-2232076));
        this.original_name.put("B00", "Frost Blue");
        this.original_color.put("B01", app.color(-2691342));
        this.original_name.put("B01", "Mint Blue");
        this.original_color.put("B02", app.color(-4987919));
        this.original_name.put("B02", "Robin&#39;s Egg Blue");
        this.original_color.put("B04", app.color(-9187354));
        this.original_name.put("B04", "Tahitian Blue");
        this.original_color.put("B05", app.color(-12532250));
        this.original_name.put("B05", "Process Blue");
        this.original_color.put("B06", app.color(-16731162));
        this.original_name.put("B06", "Peacok Blue");
        this.original_color.put("B12", app.color(-3610896));
        this.original_name.put("B12", "Ice Blue");
        this.original_color.put("B14", app.color(-9318421));
        this.original_name.put("B14", "Light Blue");
        this.original_color.put("B16", app.color(-16728854));
        this.original_name.put("B16", "Cyanine Blue");
        this.original_color.put("B18", app.color(-14841141));
        this.original_name.put("B18", "Lapis Lazuli");
        this.original_color.put("B21", app.color(-2363911));
        this.original_name.put("B21", "Baby Blue");
        this.original_color.put("B23", app.color(-7159064));
        this.original_name.put("B23", "Phthalo Blue");
        this.original_color.put("B24", app.color(-7680269));
        this.original_name.put("B24", "Sky");
        this.original_color.put("B26", app.color(-10112029));
        this.original_name.put("B26", "Cobalt Blue");
        this.original_color.put("B29", app.color(-16681023));
        this.original_name.put("B29", "Ultramarine");
        this.original_color.put("B32", app.color(-1904649));
        this.original_name.put("B32", "Pale Blue");
        this.original_color.put("B34", app.color(-8207379));
        this.original_name.put("B34", "Manganese Blue");
        this.original_color.put("B37", app.color(-15372380));
        this.original_name.put("B37", "Antwerp Blue");
        this.original_color.put("B39", app.color(-13933399));
        this.original_name.put("B39", "Prussian Blue");
        this.original_color.put("B41", app.color(-1904389));
        this.original_name.put("B41", "Powder Blue");
        this.original_color.put("B45", app.color(-9060118));
        this.original_name.put("B45", "Smoky Blue");
        this.original_color.put("BG02", app.color(-3741462));
        this.original_name.put("BG02", "New Blue");
        this.original_color.put("BG05", app.color(-8138015));
        this.original_name.put("BG05", "Holiday Blue");
        this.original_color.put("BG09", app.color(-16666167));
        this.original_name.put("BG09", "Blue Green");
        this.original_color.put("BG10", app.color(-2297617));
        this.original_name.put("BG10", "Cool Shadow");
        this.original_color.put("BG11", app.color(-3216399));
        this.original_name.put("BG11", "Moon White");
        this.original_color.put("BG13", app.color(-3872791));
        this.original_name.put("BG13", "Mint Green");
        this.original_color.put("BG15", app.color(-6235694));
        this.original_name.put("BG15", "Aqua");
        this.original_color.put("BG18", app.color(-13123408));
        this.original_name.put("BG18", "Teal Blue");
        this.original_color.put("BG32", app.color(-4398377));
        this.original_name.put("BG32", "Aqua Mint");
        this.original_color.put("BG34", app.color(-6038825));
        this.original_name.put("BG34", "Horizon Green");
        this.original_color.put("BG45", app.color(-5251105));
        this.original_name.put("BG45", "Nile Blue");
        this.original_color.put("BG49", app.color(-16730439));
        this.original_name.put("BG49", "Duck Blue");
        this.original_color.put("BG99", app.color(-9528441));
        this.original_name.put("BG99", "Flagstone Blue");
        this.original_color.put("BV00", app.color(-2040595));
        this.original_name.put("BV00", "Mauve Shadow");
        this.original_color.put("BV04", app.color(-8611890));
        this.original_name.put("BV04", "Blue Berry");
        this.original_color.put("BV08", app.color(-6455623));
        this.original_name.put("BV08", "Blue Violet");
        this.original_color.put("BV23", app.color(-5127971));
        this.original_name.put("BV23", "Grayish Lavender");
        this.original_color.put("BV31", app.color(-1382414));
        this.original_name.put("BV31", "Pale Lavender");
        this.original_color.put("C0", app.color(-2037779));
        this.original_name.put("C0", "Cool Gray");
        this.original_color.put("C10", app.color(-14669007));
        this.original_name.put("C10", "Cool Gray");
        this.original_color.put("C1", app.color(-2432024));
        this.original_name.put("C1", "Cool Gray No. 1");
        this.original_color.put("C2", app.color(-3352611));
        this.original_name.put("C2", "Cool Gray");
        this.original_color.put("C3", app.color(-4076334));
        this.original_name.put("C3", "Cool Gray No. 3");
        this.original_color.put("C4", app.color(-5851971));
        this.original_name.put("C4", "Cool Gray");
        this.original_color.put("C5", app.color(-7167829));
        this.original_name.put("C5", "Cool Gray No. 5");
        this.original_color.put("C6", app.color(-8680298));
        this.original_name.put("C6", "Cool Gray");
        this.original_color.put("C7", app.color(-10260359));
        this.original_name.put("C7", "Cool Gray No. 7");
        this.original_color.put("C8", app.color(-11313818));
        this.original_name.put("C8", "Cool Gray");
        this.original_color.put("C9", app.color(-12826803));
        this.original_name.put("C9", "Cool Gray");
        this.original_color.put("E00", app.color(-134166));
        this.original_name.put("E00", "Cotton Pearl");
        this.original_color.put("E02", app.color(-70432));
        this.original_name.put("E02", "Fruit Pink");
        this.original_color.put("E04", app.color(-1786684));
        this.original_name.put("E04", "Lipstick Natural");
        this.original_color.put("E07", app.color(-3374742));
        this.original_name.put("E07", "Light Mahogany");
        this.original_color.put("E09", app.color(-2528689));
        this.original_name.put("E09", "Burnt Sienna");
        this.original_color.put("E11", app.color(-71210));
        this.original_name.put("E11", "Barley Beige");
        this.original_color.put("E13", app.color(-1456721));
        this.original_name.put("E13", "Light Suntan");
        this.original_color.put("E15", app.color(-279667));
        this.original_name.put("E15", "Dark Suntan");
        this.original_color.put("E19", app.color(-3911112));
        this.original_name.put("E19", "Redwood");
        this.original_color.put("E21", app.color(-138553));
        this.original_name.put("E21", "Soft Sun");
        this.original_color.put("E25", app.color(-2972542));
        this.original_name.put("E25", "Caribe Cocoa");
        this.original_color.put("E27", app.color(-6719901));
        this.original_name.put("E27", "Milk Chocolate");
        this.original_color.put("E29", app.color(-7846346));
        this.original_name.put("E29", "Burnt Umber");
        this.original_color.put("E31", app.color(-858418));
        this.original_name.put("E31", "Brick Beige");
        this.original_color.put("E33", app.color(-798031));
        this.original_name.put("E33", "Sand");
        this.original_color.put("E34", app.color(-996698));
        this.original_name.put("E34", "Toast");
        this.original_color.put("E35", app.color(-1653853));
        this.original_name.put("E35", "Chamois");
        this.original_color.put("E37", app.color(-3370663));
        this.original_name.put("E37", "Sepia");
        this.original_color.put("E39", app.color(-3836865));
        this.original_name.put("E39", "Leather");
        this.original_color.put("E40", app.color(-857892));
        this.original_name.put("E40", "Brick White");
        this.original_color.put("E41", app.color(-69151));
        this.original_name.put("E41", "Pearl White");
        this.original_color.put("E43", app.color(-1516867));
        this.original_name.put("E43", "Dull Ivory");
        this.original_color.put("E44", app.color(-3819095));
        this.original_name.put("E44", "Clay");
        this.original_color.put("E49", app.color(-10269636));
        this.original_name.put("E49", "Dark Bark");
        this.original_color.put("E51", app.color(-70442));
        this.original_name.put("E51", "Milky White");
        this.original_color.put("E53", app.color(-792893));
        this.original_name.put("E53", "Raw Silk");
        this.original_color.put("E55", app.color(-925767));
        this.original_name.put("E55", "Light Camel");
        this.original_color.put("E57", app.color(-5143208));
        this.original_name.put("E57", "Light Walnut");
        this.original_color.put("E59", app.color(-6652052));
        this.original_name.put("E59", "Walnut");
        this.original_color.put("E77", app.color(-8429490));
        this.original_name.put("E77", "Maroon");
        this.original_color.put("G00", app.color(-1838355));
        this.original_name.put("G00", "Jade Green");
        this.original_color.put("G02", app.color(-3151661));
        this.original_name.put("G02", "Spectrum Green");
        this.original_color.put("G05", app.color(-9846661));
        this.original_name.put("G05", "Emerald Green");
        this.original_color.put("G07", app.color(-8665738));
        this.original_name.put("G07", "Nile Green");
        this.original_color.put("G09", app.color(-8731547));
        this.original_name.put("G09", "Veronese Green");
        this.original_color.put("G12", app.color(-2955068));
        this.original_name.put("G12", "Sea Green");
        this.original_color.put("G14", app.color(-6828144));
        this.original_name.put("G14", "Apple Green");
        this.original_color.put("G16", app.color(-10436200));
        this.original_name.put("G16", "Malachite");
        this.original_color.put("G17", app.color(-15420547));
        this.original_name.put("G17", "Forest Green");
        this.original_color.put("G19", app.color(-13780598));
        this.original_name.put("G19", "Bright Parrot Green");
        this.original_color.put("G20", app.color(-1181989));
        this.original_name.put("G20", "Wax White");
        this.original_color.put("G21", app.color(-3873587));
        this.original_name.put("G21", "Lime Green");
        this.original_color.put("G24", app.color(-3940172));
        this.original_name.put("G24", "Willow");
        this.original_color.put("G28", app.color(-15625118));
        this.original_name.put("G28", "Ocean Green");
        this.original_color.put("G29", app.color(-15106979));
        this.original_name.put("G29", "Pine Tree Green");
        this.original_color.put("G40", app.color(-1773089));
        this.original_name.put("G40", "Dim Green");
        this.original_color.put("G82", app.color(-3351879));
        this.original_name.put("G82", "Spring Dim Green");
        this.original_color.put("G85", app.color(-6437974));
        this.original_name.put("G85", "Verdigris");
        this.original_color.put("G99", app.color(-10518982));
        this.original_name.put("G99", "Olive");
        this.original_color.put("N0", app.color(-1249555));
        this.original_name.put("N0", "Neutral Gray");
        this.original_color.put("N10", app.color(-13553872));
        this.original_name.put("N10", "Neutral Gray");
        this.original_color.put("N1", app.color(-1907739));
        this.original_name.put("N1", "Neutral Gray");
        this.original_color.put("N2", app.color(-2434083));
        this.original_name.put("N2", "Neutral Gray");
        this.original_color.put("N3", app.color(-3026220));
        this.original_name.put("N3", "Neutral Gray");
        this.original_color.put("N4", app.color(-4407871));
        this.original_name.put("N4", "Neutral Gray");
        this.original_color.put("N5", app.color(-5723731));
        this.original_name.put("N5", "Neutral Gray");
        this.original_color.put("N6", app.color(-7039591));
        this.original_name.put("N6", "Neutral Gray");
        this.original_color.put("N7", app.color(-8947588));
        this.original_name.put("N7", "Neutral Gray");
        this.original_color.put("N8", app.color(-10263450));
        this.original_name.put("N8", "Neutral Gray");
        this.original_color.put("N9", app.color(-11776689));
        this.original_name.put("N9", "Neutral Gray");
        this.original_color.put("R00", app.color(-70943));
        this.original_name.put("R00", "Pinkish White");
        this.original_color.put("R02", app.color(-142393));
        this.original_name.put("R02", "Rose Salmon");
        this.original_color.put("R05", app.color(-617861));
        this.original_name.put("R05", "Salmon Red");
        this.original_color.put("R08", app.color(-891052));
        this.original_name.put("R08", "Vermilion");
        this.original_color.put("R11", app.color(-138795));
        this.original_name.put("R11", "Pale Cherry Pink");
        this.original_color.put("R17", app.color(-752532));
        this.original_name.put("R17", "Lipstick Orange");
        this.original_color.put("R20", app.color(-206897));
        this.original_name.put("R20", "Blush");
        this.original_color.put("R24", app.color(-887431));
        this.original_name.put("R24", "Prawn");
        this.original_color.put("R27", app.color(-962462));
        this.original_name.put("R27", "Cadmium Red");
        this.original_color.put("R29", app.color(-1239221));
        this.original_name.put("R29", "Lipstick Red");
        this.original_color.put("R32", app.color(-343622));
        this.original_name.put("R32", "Peach");
        this.original_color.put("R35", app.color(-888443));
        this.original_name.put("R35", "Coral");
        this.original_color.put("R37", app.color(-1545100));
        this.original_name.put("R37", "Carmine");
        this.original_color.put("R39", app.color(-3454854));
        this.original_name.put("R39", "Garnet");
        this.original_color.put("R59", app.color(-4763792));
        this.original_name.put("R59", "Cardinal");
        this.original_color.put("RV02", app.color(-338458));
        this.original_name.put("RV02", "Sugared Almond Pink");
        this.original_color.put("RV04", app.color(-613441));
        this.original_name.put("RV04", "Shock  Pink");
        this.original_color.put("RV06", app.color(-817489));
        this.original_name.put("RV06", "Cerise");
        this.original_color.put("RV09", app.color(-2002516));
        this.original_name.put("RV09", "Fuchsia");
        this.original_color.put("RV10", app.color(-135948));
        this.original_name.put("RV10", "Pale Pink");
        this.original_color.put("RV11", app.color(-272675));
        this.original_name.put("RV11", "Pink");
        this.original_color.put("RV13", app.color(-407081));
        this.original_name.put("RV13", "Tender Pink");
        this.original_color.put("RV14", app.color(-748105));
        this.original_name.put("RV14", "Begonia Pink");
        this.original_color.put("RV17", app.color(-2392397));
        this.original_name.put("RV17", "Deep Magenta");
        this.original_color.put("RV19", app.color(-2987862));
        this.original_name.put("RV19", "Red Violet");
        this.original_color.put("RV21", app.color(-136985));
        this.original_name.put("RV21", "Light Pink");
        this.original_color.put("RV25", app.color(-748610));
        this.original_name.put("RV25", "Dog Rose Flower");
        this.original_color.put("RV29", app.color(-1095552));
        this.original_name.put("RV29", "Crimson");
        this.original_color.put("RV32", app.color(-338994));
        this.original_name.put("RV32", "Shadow Pink");
        this.original_color.put("RV34", app.color(-413778));
        this.original_name.put("RV34", "Dark Pink");
        this.original_color.put("T0", app.color(-1249555));
        this.original_name.put("T0", "Toner Gray");
        this.original_color.put("T10", app.color(-13488595));
        this.original_name.put("T10", "Toner Gray");
        this.original_color.put("T1", app.color(-1381656));
        this.original_name.put("T1", "Toner Gray");
        this.original_color.put("T2", app.color(-2039586));
        this.original_name.put("T2", "Toner Gray");
        this.original_color.put("T3", app.color(-3026228));
        this.original_name.put("T3", "Toner Gray");
        this.original_color.put("T4", app.color(-4408391));
        this.original_name.put("T4", "Toner Gray");
        this.original_color.put("T5", app.color(-5724253));
        this.original_name.put("T5", "Toner Gray");
        this.original_color.put("T6", app.color(-7039600));
        this.original_name.put("T6", "Toner Gray");
        this.original_color.put("T7", app.color(-8948108));
        this.original_name.put("T7", "Toner Gray");
        this.original_color.put("T8", app.color(-10263457));
        this.original_name.put("T8", "Toner Gray");
        this.original_color.put("T9", app.color(-11777207));
        this.original_name.put("T9", "Toner Gray");
        this.original_color.put("V04", app.color(-1660210));
        this.original_name.put("V04", "Lilac");
        this.original_color.put("V06", app.color(-3238462));
        this.original_name.put("V06", "Lavender");
        this.original_color.put("V09", app.color(-7908191));
        this.original_name.put("V09", "Violet");
        this.original_color.put("V12", app.color(-1124375));
        this.original_name.put("V12", "Pale Lilac");
        this.original_color.put("V15", app.color(-2906419));
        this.original_name.put("V15", "Mallow");
        this.original_color.put("V17", app.color(-6253881));
        this.original_name.put("V17", "Amethyst");
        this.original_color.put("W0", app.color(-1250076));
        this.original_name.put("W0", "Warm Gray");
        this.original_color.put("W10", app.color(-13619413));
        this.original_name.put("W10", "Warm Gray");
        this.original_color.put("W1", app.color(-1579041));
        this.original_name.put("W1", "Warm Gray No. 1");
        this.original_color.put("W2", app.color(-2236971));
        this.original_name.put("W2", "Warm Gray");
        this.original_color.put("W3", app.color(-2960694));
        this.original_name.put("W3", "Warm Gray No. 3");
        this.original_color.put("W4", app.color(-4407881));
        this.original_name.put("W4", "Warm Gray");
        this.original_color.put("W5", app.color(-5723740));
        this.original_name.put("W5", "Warm Gray No. 5");
        this.original_color.put("W6", app.color(-7039601));
        this.original_name.put("W6", "Warm Gray");
        this.original_color.put("W7", app.color(-8947597));
        this.original_name.put("W7", "Warm Gray No. 7");
        this.original_color.put("W8", app.color(-10263457));
        this.original_name.put("W8", "Warm Gray");
        this.original_color.put("W9", app.color(-11776696));
        this.original_name.put("W9", "Warm Gray");
        this.original_color.put("Y00", app.color(-66081));
        this.original_name.put("Y00", "Barium Yellow");
        this.original_color.put("Y02", app.color(-593002));
        this.original_name.put("Y02", "Canary Yellow");
        this.original_color.put("Y06", app.color(-68244));
        this.original_name.put("Y06", "Yellow");
        this.original_color.put("Y08", app.color(-69120));
        this.original_name.put("Y08", "Acid Yellow");
        this.original_color.put("Y11", app.color(-1076));
        this.original_name.put("Y11", "Pale Yellow");
        this.original_color.put("Y13", app.color(-264274));
        this.original_name.put("Y13", "Lemon Yellow");
        this.original_color.put("Y15", app.color(-71316));
        this.original_name.put("Y15", "Cadmium Yellow");
        this.original_color.put("Y17", app.color(-7083));
        this.original_name.put("Y17", "Golden Yellow");
        this.original_color.put("Y19", app.color(-5826));
        this.original_name.put("Y19", "Napoli Yellow");
        this.original_color.put("Y21", app.color(-4414));
        this.original_name.put("Y21", "Buttercup Yellow");
        this.original_color.put("Y23", app.color(-269389));
        this.original_name.put("Y23", "Yellowish Beige");
        this.original_color.put("Y26", app.color(-991897));
        this.original_name.put("Y26", "Mustard");
        this.original_color.put("Y38", app.color(-11404));
        this.original_name.put("Y38", "Honey");
        this.original_color.put("YG01", app.color(-1905742));
        this.original_name.put("YG01", "Green Bice");
        this.original_color.put("YG03", app.color(-2168150));
        this.original_name.put("YG03", "Yellow Green");
        this.original_color.put("YG05", app.color(-2693742));
        this.original_name.put("YG05", "Salad");
        this.original_color.put("YG07", app.color(-5910705));
        this.original_name.put("YG07", "Acid Green");
        this.original_color.put("YG09", app.color(-8207002));
        this.original_name.put("YG09", "Lettuce Green");
        this.original_color.put("YG11", app.color(-1707824));
        this.original_name.put("YG11", "Mignonette");
        this.original_color.put("YG13", app.color(-2824801));
        this.original_name.put("YG13", "Chartreuse");
        this.original_color.put("YG17", app.color(-9256618));
        this.original_name.put("YG17", "Grass Green");
        this.original_color.put("YG21", app.color(-526658));
        this.original_name.put("YG21", "Anise");
        this.original_color.put("YG23", app.color(-1643633));
        this.original_name.put("YG23", "New Leaf");
        this.original_color.put("YG25", app.color(-3088005));
        this.original_name.put("YG25", "Celadon Green");
        this.original_color.put("YG41", app.color(-2757676));
        this.original_name.put("YG41", "Pale Cobalt Green");
        this.original_color.put("YG45", app.color(-4924233));
        this.original_name.put("YG45", "Cobalt Green");
        this.original_color.put("YG63", app.color(-6239582));
        this.original_name.put("YG63", "Pea Green");
        this.original_color.put("YG67", app.color(-8274036));
        this.original_name.put("YG67", "Moss");
        this.original_color.put("YG91", app.color(-2435154));
        this.original_name.put("YG91", "Putty");
        this.original_color.put("YG95", app.color(-3422626));
        this.original_name.put("YG95", "Pale Olive");
        this.original_color.put("YG97", app.color(-6975741));
        this.original_name.put("YG97", "Spanish Olive");
        this.original_color.put("YG99", app.color(-11638251));
        this.original_name.put("YG99", "Marine Green");
        this.original_color.put("YR00", app.color(-76099));
        this.original_name.put("YR00", "Powder Pink");
        this.original_color.put("YR02", app.color(-205627));
        this.original_name.put("YR02", "Light Orange");
        this.original_color.put("YR04", app.color(-81047));
        this.original_name.put("YR04", "Chrome Orange");
        this.original_color.put("YR07", app.color(-889031));
        this.original_name.put("YR07", "Cadmium Orange");
        this.original_color.put("YR09", app.color(-961244));
        this.original_name.put("YR09", "Chinese Orange");
        this.original_color.put("YR14", app.color(-79794));
        this.original_name.put("YR14", "Caramel");
        this.original_color.put("YR16", app.color(-84183));
        this.original_name.put("YR16", "Apricot");
        this.original_color.put("YR18", app.color(-890052));
        this.original_name.put("YR18", "Sanguine");
        this.original_color.put("YR21", app.color(-664143));
        this.original_name.put("YR21", "Cream");
        this.original_color.put("YR23", app.color(-1257589));
        this.original_name.put("YR23", "Yellow Ochre");
        this.original_color.put("YR24", app.color(-995484));
        this.original_name.put("YR24", "Pale Sepia");
    }

    public int get_sketch_color(String pen) {
        return sketch_color.get(pen);
    }

    public int get_original_color(String pen) {
        return original_color.get(pen);
    }

    public String get_sketch_name(String pen) {
        return sketch_name.get(pen);
    }

    public String get_original_name(String pen) {
        return original_name.get(pen);
    }

    public String get_closest_original(int c1) {
        //http://stackoverflow.com/questions/1847092/given-an-rgb-value-what-would-be-the-best-way-to-find-the-closest-match-in-the-d
        //https://en.wikipedia.org/wiki/Color_difference

        float r1 = app.red(c1);
        float g1 = app.green(c1);
        float b1 = app.blue(c1);

        float closest_value = 99999999999999999999999999.0F;
        String closest_pen = "";

        for (Map.Entry me : original_color.entrySet()) {
            //println(me.getKey() + " is " + me.getValue());

            int c2 = (int)me.getValue();
            float r2 = app.red(c2);
            float g2 = app.green(c2);
            float b2 = app.blue(c2);

            float d = sq((r2-r1)*0.30F) + sq((g2-g1)*0.59F) + sq((b2-b1)*0.11F);
            if (d<closest_value) {
                closest_value = d;
                closest_pen = (String)me.getKey();
            }
        }
        return closest_pen;
    }

    public String get_closest_sketch(int c1) {
        //http://stackoverflow.com/questions/1847092/given-an-rgb-value-what-would-be-the-best-way-to-find-the-closest-match-in-the-d
        //https://en.wikipedia.org/wiki/Color_difference

        float r1 = app.red(c1);
        float g1 = app.green(c1);
        float b1 = app.blue(c1);

        float closest_value = 99999999999999999999999999.0F;
        String closest_pen = "";

        for (Map.Entry me : sketch_color.entrySet()) {
            //println(me.getKey() + " is " + me.getValue());

            int c2 = (int)me.getValue();
            float r2 = app.red(c2);
            float g2 = app.green(c2);
            float b2 = app.blue(c2);

            float d = sq(abs((r2-r1))*0.30F) + sq(abs((g2-g1))*0.59F) + sq(abs((b2-b1))*0.11F);
            //float d = sq((r2-r1)*0.30) + sq((g2-g1)*0.59) + sq((b2-b1)*0.11);
            if (d<closest_value) {
                closest_value = d;
                closest_pen = (String)me.getKey();
            }
        }
        return closest_pen;
    }



    public void copic_alpha_simulator() {
        int[] p = new int[5];
        p[0] = app.copic.get_original_color("N1");
        p[1] = app.copic.get_original_color("N3");
        p[2] = app.copic.get_original_color("N5");
        p[3] = app.copic.get_original_color("N7");
        p[4] = app.copic.get_original_color("100");

        int alpha = 210;
        int pen_off=200;
        int off=30;

        for (int pen=0; pen<5; pen++) {
            for (int x=0; x<5; x++) {
                //fill(p[pen], alpha);  rect(pen*150+10, pen*off+x*pen_off, 500, 80);
                app.stroke(p[pen], alpha);
                app.strokeWeight(50);
                app.fill(p[4], 50);
                app.line(pen*150+10, pen*off+x*pen_off, pen*150+10+500, pen*off+x*pen_off);
            }
        }
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////////////
    public void test_draw_closest_copic_color() {
        app.noStroke();

        for (int i = 0; i < 255; i++) {
            app.colorMode(HSB, 255);
            int c1 = app.color(i, app.mouseX, app.mouseY);
            //color c1 = color(mouseX, i, mouseY);
            //color c1 = color(mouseX, mouseY, i);
            app.fill(c1);
            app.rect(i*5, 0, 5, 100);

            String p = app.copic.get_closest_original(c1);
            //println(p + "   " + c.get_original_name(p));
            int c2 = app.copic.get_original_color(p);
            app.fill(c2);
            app.rect(i*5, 105, 5, 100);
        }
    }

///////////////////////////////////////////////////////////////////////////////////////////////////////

}
///////////////////////////////////////////////////////////////////////////////////////////////////////